import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import { cn } from "@/lib/utils";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { AllProviders } from "@/providers";

const montserrat = Montserrat({
  weight: "400",
  display: "auto",
  subsets: ["latin"],
}); //  subsets: ["latin"]

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(montserrat.className, "h-screen  ")}>
        <AllProviders>
          {children}
          <Toaster />
        </AllProviders>
      </body>
    </html>
  );
}
