import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import { cn } from "@/lib/utils";

const poppins = Poppins({ weight: "400", display: "auto", subsets: ["latin"] }); //  subsets: ["latin"]

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(poppins.className, "h-screen  ")}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
